[package]
name = "lonlat_bng"
description = "Convert longitude and latitude coordinates to BNG coordinates"
version = "0.1.0"
authors = ["Stephan Hügel <urschrei@gmail.com>"]

[lib]
name = "lonlat_bng"
crate-type = ["dylib"]
test = true
doctest = true
doc = true

